project_id          = "mystic-castle-460413-g6"
region              = "us-central1"
zone                = "us-central1-a"
cluster_name        = "chatbot-cluster"
frontend_image_path = "gcr.io/${var.project_id}/streamlit-chatbot:latest"
ollama_image_path   = "gcr.io/${var.project_id}/ollama-server:latest"