apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-llm-chatbot
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-llm-chatbot
  template:
    metadata:
      labels:
        app: gke-llm-chatbot
    spec:
      containers:
        - name: gke-llm-chatbot
          image: gke-llm-chatbot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
