name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-gcp-impersonation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Inspect OIDC Token Claims
      run: |
        echo "${ID_TOKEN}" | cut -d '.' -f2 | base64 -d | jq
      shell: bash
      env:
        ID_TOKEN: ${{ steps.auth.outputs.id_token }}

    - name: Dump OIDC token claims
      run: |
        TOKEN=$(curl -s "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://github.com/${{ github.repository }}" \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r .value)
  
        echo "$TOKEN" | cut -d '.' -f2 | base64 -d | jq

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/761983095080/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-actions-oidc-provider'
        service_account: 'deployment-service-account@mystic-castle-460413-g6.iam.gserviceaccount.com'
    
    - name: set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: List GCS Buckets
      run: gcloud storage buckets list
    