name: CI/CD pipeline

on:
  push:
    # paths:
    #   - 'iac/tf/**'
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: CI - Terraform Lint & Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_IMPERSONATOR_SA }}
    
    # - name: set up gcloud
    #   uses: google-github-actions/setup-gcloud@v2
    
    # - name: Assume deployment service account
    #   run: |
    #     gcloud config set auth/impersonate_service_account ${{ secrets.GCP_DEPLOYMENT_SA }}
    
    - name: Run CI checks
      uses: augustinechiajh/gha-ci-tf@main
      with:
        terraform-work-dir: 'iac/tf'

  cd:
    name: CD - Terraform Deployment Workflow
    needs: ci
    uses: augustinechiajh/gha-cd-tf/.github/workflows/terraform-deployment-gcp.yaml@main
    with:
      environment: dev
      terraform-work-dir: 'iac/tf'
      is-destroy: true
      debug-logs: true
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_IMPERSONATOR_SA: ${{ secrets.GCP_IMPERSONATOR_SA }}