name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-gcp-impersonation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/761983095080/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-actions-oidc-provider'
        service_account: 'gha-impersonator@mystic-castle-460413-g6.iam.gserviceaccount.com'
    
    - name: set up gcloud
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Assume deployment service account
      run: |
        gcloud config set auth/impersonate_service_account deployment-service-account@mystic-castle-460413-g6.iam.gserviceaccount.com

    - name: Run CI checks
      uses: augustinechiajh/gha-ci-tf@main
      with:
        terraform-work-dir: 'iac/tf'
    